import { Inter_Tight } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';

const inter = Inter_Tight({ subsets: ['latin'], variable: '--font-inter' });
const display = localFont({
  src: './display.ttf',
  variable: '--font-display',
  display: 'swap',
});

export const metadata = {
  title: 'AKDMY',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${display.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
